server.port : 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: HOTEL-SERVICE
          uri: "http://localhost:9001"
          predicates:
            - Path= /hotels/**
          filters:
            - name: CircuitBreaker
              args:
                name: HOTEL-SERVICE
                fallbackuri: forward:/hotelServiceFallBackMethod
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka.client.registerWithEureka: true
eureka.client.fetchRegistry: true
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
eureka.instance.hostname: localhost


