server.port : 9191

spring:
  application:
    name: API-GATEWAY
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: HOTEL-SERVICE
          uri: "http://localhost:9001"
          predicates:
            - Path= /hotels/**
          filters:
            - name: CircuitBreaker
              args:
                name: HOTEL-SERVICE
                fallbackuri: forward:/hotelServiceFallBackMethod
        - id: GUEST-SERVICE
          uri: "http://localhost:9003"
          predicates:
            - Path= /guests/**
          filters:
            - name: CircuitBreaker
              args:
                name: GUEST-SERVICE
                fallbackuri: forward:/guestServiceFallBackMethod
        - id: RESERVATION-SERVICE
          uri: "http://localhost:9004"
          predicates:
            - Path= /reservations/**
          filters:
            - name: CircuitBreaker
              args:
                name: RESERVATION-SERVICE
                fallbackuri: forward:/reservationServiceFallBackMethod

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    backends:
      hotelServiceFallBackMethod:
        register-health-indicator: true
      guestServiceFallBackMethod:
        register-health-indicator: true
      reservationServiceFallBackMethod:
        register-health-indicator: true



